#!/bin/bash
# Docker-based installation script for Blitz Node
# Mirrors install.sh logic while provisioning Docker assets

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${REPO_ROOT}/hysteria-config"
ENV_FILE="${REPO_ROOT}/.env"
COMPOSE_FILE="${REPO_ROOT}/docker-compose.yml"
DOCKER="${DOCKER:-docker}"
DOCKER_COMPOSE="${DOCKER_COMPOSE:-docker compose}"

CONFIG_TEMPLATE_URL="https://raw.githubusercontent.com/ReturnFI/Blitz/main/config.json"
GEOSITE_URL="https://raw.githubusercontent.com/Chocolate4U/Iran-v2ray-rules/release/geosite.dat"
GEOIP_URL="https://raw.githubusercontent.com/Chocolate4U/Iran-v2ray-rules/release/geoip.dat"

usage() {
    cat <<EOF
Usage: $0 install <port> <sni>
       $0 uninstall

Options:
  install   Install Blitz Node stack via Docker
  uninstall Remove containers, volumes, and generated config

Examples:
  $0 install 1239 example.com
  $0 uninstall
EOF
}

run_with_privileges() {
    if [[ $EUID -eq 0 ]]; then
        "$@"
    elif command -v sudo >/dev/null 2>&1; then
        sudo "$@"
    else
        echo "This operation requires elevated privileges: $*" >&2
        exit 1
    fi
}

apt_update_ran=false

ensure_apt_packages() {
    local packages=("$@")
    if command -v apt-get >/dev/null 2>&1; then
        if [[ $apt_update_ran = false ]]; then
            run_with_privileges apt-get update
            apt_update_ran=true
        fi
        run_with_privileges apt-get install -y "${packages[@]}"
    else
        echo "Automatic dependency installation is only implemented for apt-based systems." >&2
        exit 1
    fi
}

ensure_command() {
    local cmd="$1"
    local package="$2"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "Installing missing dependency: $package"
        ensure_apt_packages "$package"
    fi
}

install_docker_via_script() {
    echo "Installing Docker using the official convenience script..."
    run_with_privileges sh -c "curl -fsSL https://get.docker.com | sh"
}

ensure_docker() {
    if ! command -v "$DOCKER" >/dev/null 2>&1; then
        ensure_command "curl" "curl"
        install_docker_via_script
    elif ! $DOCKER --version >/dev/null 2>&1; then
        echo "Detected docker command but unable to execute it." >&2
        exit 1
    fi

    if command -v systemctl >/dev/null 2>&1; then
        run_with_privileges systemctl enable --now docker
    fi

    local target_user="${SUDO_USER:-$USER}"
    if [[ -n "${target_user:-}" && "$target_user" != "root" ]]; then
        if command -v id >/dev/null 2>&1 && ! id -nG "$target_user" | grep -qw docker; then
            echo "Adding $target_user to docker group..."
            run_with_privileges usermod -aG docker "$target_user"
            echo "Please log out and log back in for the group change to take effect."
        fi
    fi
}

install_compose_plugin() {
    if command -v apt-get >/dev/null 2>&1; then
        echo "Attempting to install docker compose plugin via apt..."
        if run_with_privileges apt-get install -y docker-compose-plugin; then
            DOCKER_COMPOSE="docker compose"
            return 0
        fi
    fi
    return 1
}

install_compose_standalone() {
    echo "Installing standalone docker-compose binary..."
    local arch
    arch=$(uname -m)
    case "$arch" in
        x86_64|amd64) arch="x86_64" ;;
        aarch64|arm64) arch="aarch64" ;;
        armv7l) arch="armv7" ;;
        *) echo "Unsupported architecture for docker-compose binary: $arch" >&2; return 1 ;;
    esac

    local version="v2.24.7"
    local url="https://github.com/docker/compose/releases/download/${version}/docker-compose-linux-${arch}"
    run_with_privileges curl -fsSL "$url" -o /usr/local/bin/docker-compose
    run_with_privileges chmod +x /usr/local/bin/docker-compose
    DOCKER_COMPOSE="docker-compose"
}

ensure_compose() {
    if $DOCKER_COMPOSE version >/dev/null 2>&1; then
        return
    fi

    if command -v docker compose >/dev/null 2>&1; then
        DOCKER_COMPOSE="docker compose"
        return
    fi

    if command -v docker-compose >/dev/null 2>&1; then
        DOCKER_COMPOSE="docker-compose"
        return
    fi

    ensure_command "curl" "curl"

    if install_compose_plugin; then
        return
    fi

    if install_compose_standalone; then
        return
    fi

    echo "Failed to install Docker Compose." >&2
    exit 1
}

check_requirements() {
    ensure_command "curl" "curl"
    ensure_docker
    ensure_compose
    ensure_command "jq" "jq"
    ensure_command "openssl" "openssl"
    ensure_command "uuidgen" "uuid-runtime"
}

generate_env_file() {
    local panel_url="$1"
    local panel_key="$2"
    local port="$3"
    local sni="$4"

    if [[ -f "$ENV_FILE" ]]; then
        echo ".env already exists. Skipping creation."
        return
    fi

    cat > "$ENV_FILE" <<EOF
# Generated by dockerize.sh
PANEL_API_URL=${panel_url%/}/api/v1/users/
PANEL_TRAFFIC_URL=${panel_url%/}/api/v1/config/ip/nodestraffic
PANEL_API_KEY=${panel_key}

HYSTERIA_VERSION=v2.4.1
HYSTERIA_PORT=${port}
HYSTERIA_SNI=${sni}

AUTH_PORT=28262

SYNC_INTERVAL=60
HYSTERIA_API_BASE=http://hysteria:25413
HYSTERIA_CONFIG_FILE=/etc/hysteria/config.json
EOF
}

download_assets() {
    mkdir -p "$CONFIG_DIR"

    if [[ ! -f "${CONFIG_DIR}/config.json" ]]; then
        curl -fsSL "$CONFIG_TEMPLATE_URL" -o "${CONFIG_DIR}/config.json"
    fi

    if [[ ! -f "${CONFIG_DIR}/geoip.dat" ]]; then
        curl -fsSL "$GEOIP_URL" -o "${CONFIG_DIR}/geoip.dat"
    fi

    if [[ ! -f "${CONFIG_DIR}/geosite.dat" ]]; then
        curl -fsSL "$GEOSITE_URL" -o "${CONFIG_DIR}/geosite.dat"
    fi
}

generate_tls_assets() {
    local sni="$1"
    local cert_path="${CONFIG_DIR}/ca.crt"
    local key_path="${CONFIG_DIR}/ca.key"

    if [[ ! -f "$key_path" || ! -f "$cert_path" ]]; then
        openssl ecparam -genkey -name prime256v1 -out "$key_path"
        openssl req -new -x509 -days 36500 -key "$key_path" -out "$cert_path" -subj "/CN=${sni}"
    fi
}

customize_config() {
    local port="$1"
    local sni="$2"
    local sha256
    local obfs_password
    local uuid_value
    local network_device

    uuid_value=$(uuidgen)
    obfs_password=$(openssl rand -base64 24)
    sha256=$(openssl x509 -noout -fingerprint -sha256 -inform pem -in "${CONFIG_DIR}/ca.crt" | sed 's/.*=//' | tr '[:lower:]' '[:upper:]')
    if command -v ip >/dev/null 2>&1; then
        network_device=$(ip route | grep "^default" | awk '{print $5}' | head -n1)
    else
        network_device=""
    fi

    tmp_file=$(mktemp)
    jq \
        --arg port "$port" \
        --arg sha256 "$sha256" \
        --arg obfspassword "$obfs_password" \
        --arg UUID "$uuid_value" \
        --arg networkdef "$network_device" \
        '.listen = (":" + $port) |
         .tls.cert = "/etc/hysteria/ca.crt" |
         .tls.key = "/etc/hysteria/ca.key" |
         .tls.pinSHA256 = $sha256 |
         .obfs.salamander.password = $obfspassword |
         .trafficStats.secret = $UUID |
         (if $networkdef != "" then .outbounds[0].direct.bindDevice = $networkdef else . end)' \
        "${CONFIG_DIR}/config.json" > "$tmp_file"
    mv "$tmp_file" "${CONFIG_DIR}/config.json"
}

generate_docker_compose() {
    cat > "$COMPOSE_FILE" <<'EOF'
services:
  hysteria:
    build:
      context: .
      target: hysteria
      args:
        HYSTERIA_VERSION: ${HYSTERIA_VERSION:-v2.4.1}
    image: blitz-hysteria:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./hysteria-config:/etc/hysteria
    ports:
      - "${HYSTERIA_PORT:-1239}:${HYSTERIA_PORT:-1239}/udp"

  auth:
    build:
      context: .
      target: app
    image: blitz-node:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      AUTH_HOST: 0.0.0.0
      AUTH_PORT: ${AUTH_PORT:-28262}
    ports:
      - "${AUTH_PORT:-28262}:28262"
    volumes:
      - ./hysteria-config:/etc/hysteria:ro
    depends_on:
      - hysteria

  traffic:
    build:
      context: .
      target: app
    image: blitz-node:latest
    restart: unless-stopped
    env_file:
      - .env
    command: traffic.py
    environment:
      HYSTERIA_CONFIG_FILE: ${HYSTERIA_CONFIG_FILE:-/etc/hysteria/config.json}
      SYNC_INTERVAL: ${SYNC_INTERVAL:-60}
      HYSTERIA_API_BASE: ${HYSTERIA_API_BASE:-http://hysteria:25413}
    depends_on:
      - hysteria
    volumes:
      - ./hysteria-config:/etc/hysteria:ro
EOF
}

install_stack() {
    local port="$1"
    local sni="$2"
    local panel_url
    local panel_key

    read -rp "Enter panel API domain and path (e.g., https://example.com/path/): " panel_url
    read -rp "Enter panel API key: " panel_key

    if [[ -z "$panel_url" || -z "$panel_key" ]]; then
        echo "Panel URL and API key are required." >&2
        exit 1
    fi

    check_requirements
    download_assets
    generate_tls_assets "$sni"
    customize_config "$port" "$sni"
    generate_env_file "$panel_url" "$panel_key" "$port" "$sni"
    generate_docker_compose

    echo "Building Docker images..."
    $DOCKER_COMPOSE -f "$COMPOSE_FILE" build

    echo "Starting services..."
    $DOCKER_COMPOSE -f "$COMPOSE_FILE" up -d

    echo "Installation complete."
}

uninstall_stack() {
    if [[ -f "$COMPOSE_FILE" ]]; then
        $DOCKER_COMPOSE -f "$COMPOSE_FILE" down
    fi

    rm -f "$ENV_FILE"
    rm -rf "$CONFIG_DIR"
    echo "Docker stack removed."
}

main() {
    case "${1:-}" in
        install)
            if [[ -z "${2:-}" || -z "${3:-}" ]]; then
                echo "Port and SNI required."
                usage
                exit 1
            fi
            install_stack "$2" "$3"
            ;;
        uninstall)
            uninstall_stack
            ;;
        -h|--help)
            usage
            ;;
        *)
            usage
            exit 1
            ;;
    esac
}

main "$@"

